
spring:
  profiles:
    active: "docker"
  cloud:
    stream:
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json

server:
  port: 8080

---

# Default profile
spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 127.0.0.1:2181
          brokers: 127.0.0.1:9092
          defaultZkPort: 2181
          defaultBrokerPort: 9092

---

# Docker profile
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 192.168.99.100:2181
          brokers: 192.168.99.100:9092
          defaultZkPort: 2181
          defaultBrokerPort: 9092